export const GET_ALBUMS_REQUEST = 'GET_ALBUMS_REQUEST';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAILED = 'GET_ALBUMS_FAILED';

export const GET_ALBUM_PHOTOS_REQUEST = 'GET_ALBUM_PHOTOS_REQUEST';
export const GET_ALBUM_PHOTOS_SUCCESS = 'GET_ALBUM_PHOTOS_SUCCESS';
export const GET_ALBUM_PHOTOS_FAILED = 'GET_ALBUM_PHOTOS_FAILED';